runtime: go111
instance_class: B1
automatic_scaling:
  max_instances: 2
  max_idle_instances: 1
  max_concurrent_requests: 50

handlers:
- url: /.well-known
  static_dir: well-known

- url: /js
  static_dir: js

- url: /.*
  script: auto
